---
language: ruby
rvm: 2.4.1
script:
  - "bundle exec rake"
  - "bundle exec mdl -c .mdlrc _posts/"
notifications:
  email:
    recipients:
      - 'alexharv074@gmail.com'
    on_success: never
    on_failure: always
